In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("C:/Users/Gaurang Vaghela/OneDrive/Desktop/Dataset/autodata.csv")
df

,Unnamed: 0,symboling,normalized-losses,make,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price,city-L/100km,horsepower-binned,diesel,gas
0,0,3,122,alfa-romero,std,two,convertible,rwd,front,88.6,...,9.0,111.0,5000.0,21,27,13495.0,11.190476,Low,0,1
1,1,3,122,alfa-romero,std,two,convertible,rwd,front,88.6,...,9.0,111.0,5000.0,21,27,16500.0,11.190476,Low,0,1
2,2,1,122,alfa-romero,std,two,hatchback,rwd,front,94.5,...,9.0,154.0,5000.0,19,26,16500.0,12.368421,Medium,0,1
3,3,2,164,audi,std,four,sedan,fwd,front,99.8,...,10.0,102.0,5500.0,24,30,13950.0,9.791667,Low,0,1
4,4,2,164,audi,std,four,sedan,4wd,front,99.4,...,8.0,115.0,5500.0,18,22,17450.0,13.055556,Low,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
196,196,-1,95,volvo,std,four,sedan,rwd,front,109.1,...,9.5,114.0,5400.0,23,28,16845.0,10.217391,Low,0,1
197,197,-1,95,volvo,turbo,four,sedan,rwd,front,109.1,...,8.7,160.0,5300.0,19,25,19045.0,12.368421,Medium,0,1
198,198,-1,95,volvo,std,four,sedan,rwd,front,109.1,...,8.8,134.0,5500.0,18,23,21485.0,13.055556,Medium,0,1
199,199,-1,95,volvo,turbo,four,sedan,rwd,front,109.1,...,23.0,106.0,4800.0,26,27,22470.0,9.038462,Low,1,0
200,200,-1,95,volvo,turbo,four,sedan,rwd,front,109.1,...,9.5,114.0,5400.0,19,25,22625.0,12.368421,Low,0,1

In [3]:
df.head(10)

,Unnamed: 0,symboling,normalized-losses,make,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price,city-L/100km,horsepower-binned,diesel,gas
0,0,3,122,alfa-romero,std,two,convertible,rwd,front,88.6,...,9.0,111.0,5000.0,21,27,13495.0,11.190476,Low,0,1
1,1,3,122,alfa-romero,std,two,convertible,rwd,front,88.6,...,9.0,111.0,5000.0,21,27,16500.0,11.190476,Low,0,1
2,2,1,122,alfa-romero,std,two,hatchback,rwd,front,94.5,...,9.0,154.0,5000.0,19,26,16500.0,12.368421,Medium,0,1
3,3,2,164,audi,std,four,sedan,fwd,front,99.8,...,10.0,102.0,5500.0,24,30,13950.0,9.791667,Low,0,1
4,4,2,164,audi,std,four,sedan,4wd,front,99.4,...,8.0,115.0,5500.0,18,22,17450.0,13.055556,Low,0,1
5,5,2,122,audi,std,two,sedan,fwd,front,99.8,...,8.5,110.0,5500.0,19,25,15250.0,12.368421,Low,0,1
6,6,1,158,audi,std,four,sedan,fwd,front,105.8,...,8.5,110.0,5500.0,19,25,17710.0,12.368421,Low,0,1
7,7,1,122,audi,std,four,wagon,fwd,front,105.8,...,8.5,110.0,5500.0,19,25,18920.0,12.368421,Low,0,1
8,8,1,158,audi,turbo,four,sedan,fwd,front,105.8,...,8.3,140.0,5500.0,17,20,23875.0,13.823529,Medium,0,1
9,9,2,192,bmw,std,two,sedan,rwd,front,101.2,...,8.8,101.0,5800.0,23,29,16430.0,10.217391,Low,0,1

In [4]:
df.tail(10)

,Unnamed: 0,symboling,normalized-losses,make,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price,city-L/100km,horsepower-binned,diesel,gas
191,191,-1,74,volvo,std,four,wagon,rwd,front,104.3,...,9.5,114.0,5400.0,23,28,13415.0,10.217391,Low,0,1
192,192,-2,103,volvo,std,four,sedan,rwd,front,104.3,...,9.5,114.0,5400.0,24,28,15985.0,9.791667,Low,0,1
193,193,-1,74,volvo,std,four,wagon,rwd,front,104.3,...,9.5,114.0,5400.0,24,28,16515.0,9.791667,Low,0,1
194,194,-2,103,volvo,turbo,four,sedan,rwd,front,104.3,...,7.5,162.0,5100.0,17,22,18420.0,13.823529,Medium,0,1
195,195,-1,74,volvo,turbo,four,wagon,rwd,front,104.3,...,7.5,162.0,5100.0,17,22,18950.0,13.823529,Medium,0,1
196,196,-1,95,volvo,std,four,sedan,rwd,front,109.1,...,9.5,114.0,5400.0,23,28,16845.0,10.217391,Low,0,1
197,197,-1,95,volvo,turbo,four,sedan,rwd,front,109.1,...,8.7,160.0,5300.0,19,25,19045.0,12.368421,Medium,0,1
198,198,-1,95,volvo,std,four,sedan,rwd,front,109.1,...,8.8,134.0,5500.0,18,23,21485.0,13.055556,Medium,0,1
199,199,-1,95,volvo,turbo,four,sedan,rwd,front,109.1,...,23.0,106.0,4800.0,26,27,22470.0,9.038462,Low,1,0
200,200,-1,95,volvo,turbo,four,sedan,rwd,front,109.1,...,9.5,114.0,5400.0,19,25,22625.0,12.368421,Low,0,1

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 201 entries, 0 to 200
Data columns (total 30 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0         201 non-null    int64
 1   symboling          201 non-null    int64
 2   normalized-losses  201 non-null    int64
 3   make               201 non-null    object
 4   aspiration         201 non-null    object
 5   num-of-doors       201 non-null    object
 6   body-style         201 non-null    object
 7   drive-wheels       201 non-null    object
 8   engine-location    201 non-null    object
 9   wheel-base         201 non-null    float64
 10  length             201 non-null    float64
 11  width              201 non-null    float64
 12  height             201 non-null    float64
 13  curb-weight        201 non-null    int64
 14  engine-type        201 non-null    object
 15  num-of-cylinders   201 non-null    object
 16  engine-size        201 non-null    int64
 17  fuel-system        201 non-null    object
 18  bore               201 non-null    float64
 19  stroke             197 non-null    float64
 20  compression-ratio  201 non-null    float64
 21  horsepower         199 non-null    float64
 22  peak-rpm           199 non-null    float64
 23  city-mpg           201 non-null    int64
 24  highway-mpg        201 non-null    int64
 25  price              201 non-null    float64
 26  city-L/100km       201 non-null    float64
 27  horsepower-binned  199 non-null    object
 28  diesel             201 non-null    int64
 29  gas                201 non-null    int64
dtypes: float64(11), int64(9), object(10)
memory usage: 47.2+ KB

In [6]:
df.isnull().sum()

Unnamed: 0           0
symboling            0
normalized-losses    0
make                 0
aspiration           0
num-of-doors         0
body-style           0
drive-wheels         0
engine-location      0
wheel-base           0
length               0
width                0
height               0
curb-weight          0
engine-type          0
num-of-cylinders     0
engine-size          0
fuel-system          0
bore                 0
stroke               4
compression-ratio    0
horsepower           2
peak-rpm             2
city-mpg             0
highway-mpg          0
price                0
city-L/100km         0
horsepower-binned    2
diesel               0
gas                  0
dtype: int64

In [7]:
df['horsepower'].dtype

dtype('float64')

In [8]:
Mean = df['horsepower'].mean()
df['horsepower'] = df['horsepower'].fillna(Mean)

In [9]:
df['horsepower'].isnull().sum()

0

In [10]:
df['horsepower'] = df['horsepower'].astype(int)

In [11]:
df['horsepower'].dtype

dtype('int32')

In [12]:
df.describe()

,Unnamed: 0,symboling,normalized-losses,wheel-base,length,width,height,curb-weight,engine-size,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price,city-L/100km,diesel,gas
count,201.000000,201.000000,201.00000,201.000000,201.000000,201.000000,201.000000,201.000000,201.000000,201.000000,197.000000,201.000000,201.000000,199.000000,201.000000,201.000000,201.000000,201.000000,201.000000,201.000000
mean,100.000000,0.840796,122.00000,98.797015,0.837102,0.915126,53.766667,2555.666667,126.875622,3.330692,3.256904,10.164279,103.393035,5117.587940,25.179104,30.686567,13207.129353,9.944145,0.099502,0.900498
std,58.167861,1.254802,31.99625,6.066366,0.059213,0.029187,2.447822,517.296727,41.546834,0.268072,0.319256,4.004965,37.365623,480.521824,6.423220,6.815150,7947.066342,2.534599,0.300083,0.300083
min,0.000000,-2.000000,65.00000,86.600000,0.678039,0.837500,47.800000,1488.000000,61.000000,2.540000,2.070000,7.000000,48.000000,4150.000000,13.000000,16.000000,5118.000000,4.795918,0.000000,0.000000
25%,50.000000,0.000000,101.00000,94.500000,0.801538,0.890278,52.000000,2169.000000,98.000000,3.150000,3.110000,8.600000,70.000000,4800.000000,19.000000,25.000000,7775.000000,7.833333,0.000000,1.000000
50%,100.000000,1.000000,122.00000,97.000000,0.832292,0.909722,54.100000,2414.000000,120.000000,3.310000,3.290000,9.000000,95.000000,5200.000000,24.000000,30.000000,10295.000000,9.791667,0.000000,1.000000
75%,150.000000,2.000000,137.00000,102.400000,0.881788,0.925000,55.500000,2926.000000,141.000000,3.580000,3.410000,9.400000,116.000000,5500.000000,30.000000,34.000000,16500.000000,12.368421,0.000000,1.000000
max,200.000000,3.000000,256.00000,120.900000,1.000000,1.000000,59.800000,4066.000000,326.000000,3.940000,4.170000,23.000000,262.000000,6600.000000,49.000000,54.000000,45400.000000,18.076923,1.000000,1.000000

In [13]:
df.shape

(201, 30)

In [14]:
df['num-of-doors'].value_counts()

num-of-doors
four    115
two      86
Name: count, dtype: int64

In [15]:
df['num-of-doors']=df['num-of-doors'].replace(['two','four'],[2,4])

C:\Users\Gaurang Vaghela\AppData\Local\Temp\ipykernel_15224\378555758.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['num-of-doors']=df['num-of-doors'].replace(['two','four'],[2,4])

In [16]:
df['num-of-doors']

0      2
1      2
2      2
3      4
4      4
      ..
196    4
197    4
198    4
199    4
200    4
Name: num-of-doors, Length: 201, dtype: int64